import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Specify weights you want to use
  variable: '--font-poppins', // Optional: Use CSS variable for easy styling
});


export const metadata: Metadata = {
  title: "Vakilgiri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"   suppressHydrationWarning={true}>
      <body
        className={`${poppins.className} antialiased bg-[#002537]` }
      >
        <Providers>
          {children} 
        </Providers>
      </body>
    </html>
  );
}
