name: vg-admin-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: "npm"

  #     - name: npm install, build, and test
  #       run: |
  #         # npm install
  #         # npm run build --if-present
  #          npm run test --if-present
  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: node-app
  #         path: .

  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: node-app

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /root/vg/frontend
            git checkout main
            git pull origin main --rebase
            docker-compose -p vgadmin up -d
